name: Coolify CI/CD Pipeline with Custom Docker Registry for DonoBank Frontend

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Custom Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login dr.bobosoftware.co.za -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set branch tag
        if: startsWith(github.ref, 'refs/heads/')
        run: echo "BRANCH_TAG=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
            VITE_SUPABASE_SERVICE_ROLE_KEY=${{ secrets.VITE_SUPABASE_SERVICE_ROLE_KEY }}
          tags: |
            dr.bobosoftware.co.za/donobank-web:latest
            dr.bobosoftware.co.za/donobank-web:${{ env.VERSION != '' && env.VERSION || env.BRANCH_TAG }}
